---
title: "Cleaning Cardisoma Palatability Data"
author: "Camila Vargas"
date: "10/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(data.table)
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)

## Sets R not to use scientific notations
options(scipen=999) 
```


## Read data
```{r}
excel_sheets("raw_data/Cardisoma Palatability.xlsx")


master_raw <- read_excel("raw_data/Cardisoma Palatability.xlsx", sheet = "Master") %>% 
  clean_names()

trials_25w <- read_excel("raw_data/Cardisoma Palatability.xlsx", sheet = "25w Trials") %>% clean_names()

trials_d50 <- read_excel("raw_data/Cardisoma Palatability.xlsx", sheet = "D50 Trials") %>% clean_names()

##Compare with 25s trials
sheet3 <- read_excel("raw_data/Cardisoma Palatability.xlsx", sheet = "Sheet3") %>% clean_names()

```

**Note**
Not including sheet 5 and sheet 6, as it seems to me that is summary data.

Sheet 3?? Has bait information for D50 and 25w. Is this all data in 25w Trails and D50 Trails?
How does it connect with the master data?


## Cleaning
```{r}

master_clean <- master_raw %>% 
  select(1:9) %>% 
  mutate(start_time = as_hms(tx_start),
         end_time = as_hms(tx_end)) %>% 
  select(-tx_start, -tx_end) %>% 
  rename(crab_bucket_weight = c_b_wt_g)

#start_time = format(tx_start, format = "%H:%M:%S"

sheet3_clean <- sheet3 %>% 
  select(1:5)

```

Unit of weight = Grams

```{r}
## checking

crab_count <- master_clean %>% 
  group_by(food) %>% 
  tally()
# matches summary table in xlsx

str(master_clean)

```

## Tails data
```{r}
trials_25w_clean <- trials_25w %>% 
  select(1:5)

sheet3_25w <- sheet3 %>% 
  select(1:5) %>% 
  filter(bait == "25W")

identical(trials_25w_clean,sheet3_25w)
all_equal(trials_25w_clean,sheet3_25w) ## identical data

trials_d50_clean <- trials_d50 %>% 
  select(1:5)

sheet3_d50 <- sheet3 %>% 
  select(1:5) %>% 
  filter(bait == "D50")

all_equal(sheet3_d50, trials_d50_clean)

```

Sheet 3 has data for both trials! 

## Matching bait infomramtion with master data

```{r}
 cardisome_complete <- master_clean %>% 
  left_join(sheet3_clean, by = c("crab", "food", "percent_remaining")) %>% 
  select(date, crab, crab_bucket_weight, crab_wt, bucket_wt, start_time, end_time, food, bait, percent_remaining, percent_consumed)


```


## Save data
```{r}
write_csv(cardisome_complete, here::here("clean_data/2010_palmyra_atoll_cardisoma_palatability.csv"))

```

